name: PNPM
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: GitHub Action for pnpm
        uses: znck/pnpm@v0.1.0-alpha.1
      - run: pnpm publish
