name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'Jacob Paris'
      - run: git config --global user.email 'jacob@jacobparis.com'
      - run: lerna version patch -m "[RELEASE] %s" --yes
      - run: git push